name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # Opcions: 'adopt', 'adopt-hotspot', 'adopt-openj9', 'amazon-corretto', 'azul-zulu', 'bellsoft', 'hibernate', 'temurin'

    - name: Compile Java code
      run: javac CompteCorrent.java